**Install necessary libraries and packages**

In [92]:
!pip install wandb alibi alibi-detect scikit-learn joblib

Requirement already satisfied: wandb in /usr/local/lib/python3.10/dist-packages (0.18.7)
Requirement already satisfied: alibi in /usr/local/lib/python3.10/dist-packages (0.9.6)
Requirement already satisfied: alibi-detect in /usr/local/lib/python3.10/dist-packages (0.12.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (1.4.2)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/local/lib/python3.10/dist-packages (from wandb) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (3.1.43)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.10/dist-packages (from wandb) (4.3.6)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (4.25.5)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from wandb) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (2.32.3)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (2.19.2)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.10/dist-packages (from wandb) (1.3.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from wandb) (75.1.0)
Requirement already satisfied: typing-extensions<5,>=4.4 in /usr/local/lib/python3.10/dist-packages (from wandb) (4.12.2)
Requirement already satisfied: numpy<2.0.0,>=1.16.2 in /usr/local/lib/python3.10/dist-packages (from alibi) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from alibi) (2.2.2)
Requirement already satisfied: spacy<4.0.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy[lookups]<4.0.0,>=2.0.0->alibi) (3.7.5)
Requirement already satisfied: blis<0.8.0 in /usr/local/lib/python3.10/dist-packages (from alibi) (0.7.11)
Requirement already satisfied: scikit-image<0.23,>=0.17.2 in /usr/local/lib/python3.10/dist-packages (from alibi) (0.22.0)
Requirement already satisfied: Pillow<11.0,>=5.4.1 in /usr/local/lib/python3.10/dist-packages (from alibi) (10.4.0)
Requirement already satisfied: attrs<24.0.0,>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from alibi) (23.2.0)
Requirement already satisfied: scipy<2.0.0,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from alibi) (1.13.1)
Requirement already satisfied: matplotlib<4.0.0,>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from alibi) (3.8.0)
Requirement already satisfied: dill<0.4.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from alibi) (0.3.9)
Requirement already satisfied: transformers<5.0.0,>=4.7.0 in /usr/local/lib/python3.10/dist-packages (from alibi) (4.46.3)
Requirement already satisfied: tqdm<5.0.0,>=4.28.1 in /usr/local/lib/python3.10/dist-packages (from alibi) (4.66.6)
Requirement already satisfied: opencv-python<5.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from alibi-detect) (4.10.0.84)
Requirement already satisfied: pydantic<3.0.0,>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from alibi-detect) (2.10.3)
Requirement already satisfied: toml<1.0.0,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from alibi-detect) (0.10.2)
Requirement already satisfied: catalogue<3.0.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from alibi-detect) (2.0.10)
Requirement already satisfied: numba!=0.54.0,<0.60.0,>=0.50.0 in /usr/local/lib/python3.10/dist-packages (from alibi-detect) (0.59.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from docker-pycreds>=0.4.0->wandb) (1.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.11)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.0.0->alibi) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.0.0->alibi) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.0.0->alibi) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.0.0->alibi) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.0.0->alibi) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.0.0->alibi) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.0.0->alibi) (2.8.2)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba!=0.54.0,<0.60.0,>=0.50.0->alibi-detect) (0.42.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=1.0.0->alibi) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=1.0.0->alibi) (2024.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=1.8.0->alibi-detect) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=1.8.0->alibi-detect) (2.27.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (2024.8.30)
Requirement already satisfied: networkx>=2.8 in /usr/local/lib/python3.10/dist-packages (from scikit-image<0.23,>=0.17.2->alibi) (3.4.2)
Requirement already satisfied: imageio>=2.27 in /usr/local/lib/python3.10/dist-packages (from scikit-image<0.23,>=0.17.2->alibi) (2.36.1)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.10/dist-packages (from scikit-image<0.23,>=0.17.2->alibi) (2024.9.20)
Requirement already satisfied: lazy_loader>=0.3 in /usr/local/lib/python3.10/dist-packages (from scikit-image<0.23,>=0.17.2->alibi) (0.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (1.0.11)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (2.0.10)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (2.5.0)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (0.15.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (3.1.4)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (3.5.0)
Requirement already satisfied: spacy-lookups-data<1.1.0,>=1.0.3 in /usr/local/lib/python3.10/dist-packages (from spacy[lookups]<4.0.0,>=2.0.0->alibi) (1.0.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.7.0->alibi) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.7.0->alibi) (0.26.5)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.7.0->alibi) (2024.9.11)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.7.0->alibi) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.7.0->alibi) (0.4.5)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers<5.0.0,>=4.7.0->alibi) (2024.10.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (0.1.5)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (7.0.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<4.0.0,>=2.0.0->spacy[lookups]<4.0.0,>=2.0.0->alibi) (0.1.2)

In [93]:
# Import the NumPy library for numerical operations
import numpy as np
np.__version__

'1.26.4'

In [94]:
import alibi # alibi: Library for explainability and understanding machine learning models
#TabularDrift: Used to detect data drift in numerical features using the Kolmogorov-Smirnov (KS) test
from alibi_detect.cd import ChiSquareDrift, TabularDrift # ChiSquareDrift: Used to detect data drift in categorical features
# save_detector: Used to save a drift detector object to a file
# load_detector: Used to load a saved drift detector object from a file
from alibi_detect.saving import save_detector, load_detector

In [95]:
import pandas as pd # pandas: For data manipulation and analysis
import numpy as np # numpy: For numerical computations and handling arrays
import matplotlib.pyplot as plt # matplotlib: For plotting graphs
import seaborn as sn # seaborn: For statistical data visualization

**Load the real estate dataset from a URL into a Pandas DataFrame**

In [96]:
# Load the real estate dataset from a URL into a Pandas DataFrame
Re_df = pd.read_csv( "https://raw.githubusercontent.com/karapradeepkumar/data/main/Real%20Estate%20Data%20V21.csv" )

In [97]:
# Display a summary of the DataFrame, including column data types, non-null values, and memory usage
Re_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14528 entries, 0 to 14527
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            14528 non-null  object
 1   Property Title  14528 non-null  object
 2   Price           14528 non-null  object
 3   Location        14528 non-null  object
 4   Total_Area      14528 non-null  int64
 5   Price_per_SQFT  14528 non-null  float64
 6   Description     14528 non-null  object
 7   Baths           14528 non-null  int64
 8   Balcony         14528 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 1021.6+ KB

In [98]:
# Extract and store the list of feature (column) names from the DataFrame
# Re_df.columns returns an Index object containing all column names in the DataFrame
x_features = list(Re_df.columns)

In [99]:
# Display the list of column names extracted from the DataFrame
x_features

['Name',
 'Property Title',
 'Price',
 'Location',
 'Total_Area',
 'Price_per_SQFT',
 'Description',
 'Baths',
 'Balcony']

**Specify the index of the columns which are categorical feautures**

In [100]:
# cat_vars represents the indices of categorical features in the DataFrame.
cat_vars = [0, 1, 2, 3, 6, 8]

In [101]:
# X: Feature matrix containing all columns from the DataFrame specified by x_features
# y: Target vector, in this case, the 'Price' column from the DataFrame
X = Re_df[x_features]
y = Re_df.Price

**Splitting data in training and testing data**

In [102]:
# Import train_test_split from sklearn to split data into training and testing sets
from sklearn.model_selection import train_test_split

In [143]:
# Load the Parquet file from the given URL and save it as X_train and X_prod

# File path for the Parquet file
file_path_1 = 'https://raw.githubusercontent.com/karapradeepkumar/data/main/train_data.parquet'
file_path_2 = 'https://raw.githubusercontent.com/karapradeepkumar/data/main/prod_data.parquet'

# Load the Parquet file into a DataFrame using pandas
X_train = pd.read_parquet(file_path_1)
X_prod = pd.read_parquet(file_path_2)

# Display the first 5 rows of X_train to verify the data has been loaded successfully
print(" X_train Data loaded successfully. Here are the first 5 rows:")
print(X_train.head())

# Print the shape of X_train to confirm the number of rows and columns
print(f"Training feature set (X_train) shape: {X_train.shape}")

 X_train Data loaded successfully. Here are the first 5 rows:
        City              Area_name Property_Type    Brokerage  \
0  Bangalore       Begur, Bangalore          Flat  Not Payable
1       Pune            Wakad, Pune          Flat  Not Payable
2       Pune     Keshav Nagar, Pune          Flat  Not Payable
3  Bangalore  Whitefield, Bangalore          Flat  Not Payable
4    Kolkata       Taltala, Kolkata          Flat  Not Payable

                                        Location Baths  Balcony  Total_Area  \
0             Vishwapriya Nagar, Begur,Bangalore     3        0      1260.0
1  Capital Tower,Shankar Kalat Nagar, Wakad,Pune     3        0      1030.0
2                             Keshav Nagar, Pune     3        0      1270.0
3           Prestige Ozone, Whitefield,Bangalore     3        0      1870.0
4                     Maula Ali, Taltala,Kolkata     3        0      1074.0

   Bedrooms  Floor  Price_per_SQFT
0       3.0    3.0          4920.0
1       2.0    6.0          7570.0
2       3.0    6.0          6140.0
3       3.0    9.0          9360.0
4       2.0    4.0          9310.0
Training feature set (X_train) shape: (5235, 11)

**Measure the drift**

In [144]:
 # Create a Tabular Drift detector using Alibi-Detect
    # The reference distribution is set using X_train (the training data)
    # p_val defines the threshold for drift detection (default 0.05)
cd = TabularDrift(X_train.values,
                  p_val=.05,
                  categories_per_feature=categories_per_feature)

"""
    Initializes a Tabular Drift detector to monitor drift in the production data
    when compared to the training data.

      Parameters:
    -----------
    X_train :
        The training feature matrix used as the reference distribution for drift detection.
        This is typically the data that the model was trained on.

    p_val : float, default=0.05
        The significance level (p-value) threshold for detecting drift.
        If the p-value for a feature is less than this threshold,
        the feature is considered to have drifted.

    categories_per_feature : dict, optional, default=None
        A dictionary that defines which features are categorical and their possible categories.
        If None, the detector assumes all features are numerical.

    Returns:
    --------
    cd : TabularDrift object
        A drift detector object that can be used to detect drift in new production data.
    """

'\n   Initializes a Tabular Drift detector to monitor drift in the production data \n   when compared to the training data.\n\n     Parameters:\n   -----------\n   X_train : \n       The training feature matrix used as the reference distribution for drift detection.\n       This is typically the data that the model was trained on.\n   \n   p_val : float, default=0.05\n       The significance level (p-value) threshold for detecting drift. \n       If the p-value for a feature is less than this threshold, \n       the feature is considered to have drifted.\n   \n   categories_per_feature : dict, optional, default=None\n       A dictionary that defines which features are categorical and their possible categories.\n       If None, the detector assumes all features are numerical.\n   \n   Returns:\n   --------\n   cd : TabularDrift object\n       A drift detector object that can be used to detect drift in new production data.\n   '

In [145]:
filepath = 'carsdrift'  # change to directory where detector is saved
save_detector(cd, filepath, legacy = True)

In [146]:
cd = load_detector(filepath)  # Load the saved Tabular Drift detector from the specified file path

WARNING:alibi_detect.saving._tensorflow.loading:No model found in carsdrift/model, setting `model` to `None`.

In [147]:
# cd.predict() takes the production dataset (X_prod) as input and checks for drift
# X_prod.to_numpy() converts the production DataFrame to a NumPy array since the detector expects a NumPy array
preds = cd.predict(X_prod.to_numpy())

**Printing the test results - KS test for the numerical features and chi-squared test for the categorical features**

In [155]:
# Determine the type of statistical test to display (Chi2 for categorical, K-S for numerical)
# Extract the statistical distance and p-value for the current feature from the prediction results
# Print the feature name, statistical test type, test statistic value, and p-value
for f in range(min(cd.n_features, len(x_features))):  # Iterate up to the minimum length to prevent exceeding index
    stat = 'Chi2' if f in list(categories_per_feature.keys()) else 'K-S'
    fname = x_features[f]
    stat_val, p_val = preds['data']['distance'][f], preds['data']['p_val'][f]
    print(f'{fname} -- {stat} {stat_val:.3f} -- p-value {p_val:.3f}')

"""
    Iterate over each feature in the drift detector to print the test statistics
    and p-values for both categorical and numerical features.

    Parameters:
    -----------
    f : int
        Index of the feature being evaluated.

    Process:
    --------
    - If the feature is categorical (present in categories_per_feature), use the Chi-Square (Chi2) test.
    - If the feature is numerical, use the Kolmogorov-Smirnov (K-S) test.
    - Print the feature name, type of statistical test, test statistic value, and p-value.
  """

Name -- Chi2 13.355 -- p-value 0.064
Property Title -- Chi2 1409.732 -- p-value 0.160
Price -- Chi2 2.047 -- p-value 0.359
Location -- Chi2 0.000 -- p-value 1.000
Total_Area -- K-S 0.028 -- p-value 0.267
Price_per_SQFT -- K-S 0.017 -- p-value 0.846
Description -- Chi2 0.000 -- p-value 1.000
Baths -- K-S 0.028 -- p-value 0.239
Balcony -- Chi2 17.438 -- p-value 0.042

'\n    Iterate over each feature in the drift detector to print the test statistics \n    and p-values for both categorical and numerical features.\n\n    Parameters:\n    -----------\n    f : int\n        Index of the feature being evaluated.\n\n    Process:\n    --------\n    - If the feature is categorical (present in categories_per_feature), use the Chi-Square (Chi2) test.\n    - If the feature is numerical, use the Kolmogorov-Smirnov (K-S) test.\n    - Print the feature name, type of statistical test, test statistic value, and p-value.\n  '

**Checking the distribution of Price_per_SQFT in training and production data**

In [156]:
# Count the occurrences of each unique value in the 'Price_per_SQFT' column of the training dataset (X_train)
# This provides an overview of the frequency distribution of 'Price_per_SQFT' values
X_train.Price_per_SQFT.value_counts()

Price_per_SQFT
5000.0     84
10000.0    44
6000.0     42
4000.0     39
6670.0     32
           ..
21300.0     1
9610.0      1
1740.0      1
3280.0      1
19990.0     1
Name: count, Length: 1329, dtype: int64

In [157]:
# Count the occurrences of each unique value in the 'Price_per_SQFT' column of the production dataset (X_prod)
# This provides an overview of the frequency distribution of 'Price_per_SQFT' values in the production data
X_prod.Price_per_SQFT.value_counts()

Price_per_SQFT
5000.0     23
6000.0     14
10000.0    12
4000.0     11
4580.0     11
           ..
20450.0     1
7510.0      1
9050.0      1
30950.0     1
15630.0     1
Name: count, Length: 820, dtype: int64

**Checking the distribution of Total_Area in training and production data**

In [158]:
# Count the occurrences of each unique value in the 'Total_Area' column of the training dataset (X_train)
# This provides insight into the frequency distribution of different 'Total_Area' values
X_train.Total_Area.value_counts()

Total_Area
1000.0    131
900.0     122
1200.0    120
1100.0    109
500.0     100
         ...
1178.0      1
806.0       1
1345.0      1
272.0       1
2482.0      1
Name: count, Length: 1116, dtype: int64

In [159]:
# Count the occurrences of each unique value in the 'Total_Area' column of the production dataset (X_prod)
# This provides insight into the frequency distribution of different 'Total_Area' values in the production data
X_prod.Total_Area.value_counts()

Total_Area
1000.0    59
1200.0    44
900.0     36
650.0     34
1100.0    34
          ..
1077.0     1
1570.0     1
2625.0     1
868.0      1
598.0      1
Name: count, Length: 669, dtype: int64

**Checking the distribution of Baths in training and production data**

In [160]:
# Count the occurrences of each unique value in the 'Baths' column of the training dataset (X_train)
X_train.Baths.value_counts()

Baths
3    3079
2    1812
4     162
1     123
5      39
6      20
Name: count, dtype: int64

In [161]:
# Count the occurrences of each unique value in the 'Baths' column of the production dataset (X_prod)
# This shows the frequency distribution of different 'Baths' values (e.g., 1, 2, 3 baths, etc.) in the production data
X_prod.Baths.value_counts()

Baths
3    1044
2     568
4      64
1      48
5      15
6       7
Name: count, dtype: int64

**Checking the distribution of Balcony in training and production data**

In [162]:
# Count the occurrences of each unique value in the 'Balcony' column of the training dataset (X_train)
X_train.Balcony.value_counts()

Balcony
0    5235
Name: count, dtype: int64

In [163]:
# Count the occurrences of each unique value in the 'Balcony' column of the production dataset (X_prod)
# This shows the frequency distribution of different 'Balcony' values (e.g., 0, 1, 2 balconies, etc.) in the production data
X_prod.Balcony.value_counts()

Balcony
0    1746
Name: count, dtype: int64